name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository so the action can access it
      - uses: actions/checkout@v3

      # Generates the snake GIF and SVG
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: RishabhRaj43
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Sets up Git for pushing changes
      - name: Setup Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # Commits and pushes changes
      - name: Commit and Push changes
        run: |
          git add dist/*
          git commit -m "Update contribution graph"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optionally deploy to GitHub Pages if needed
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
