name: Generate Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate GitHub contribution grid snake
        uses: Platane/snk@v2
        with:
          github_user_name: RishabhRaj43
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: output
          force: true
